version: '3.7'

services:
  currency-exchange:
    ports:
      - "8000:8000"
    container_name: master-currency-exchange
    build:
      context: currency-exchange-service/
      dockerfile: Dockerfile
    networks:
      - currency-network
    depends_on:
      - eureka-server
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
  eureka-server:
    ports:
      - "8761:8761"
    container_name: master-eureka-server
    build:
      context: eureka-server/
      dockerfile: Dockerfile
    networks:
      - currency-network
  currency-conversion-service:
    ports:
      - "8100:8100"
    container_name: master-currency-conversion
    build:
      context: currency-conversion-service/
      dockerfile: Dockerfile
    networks:
      - currency-network
    depends_on:
      - eureka-server
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
  api-gateway:
    ports:
      - "8765:8765"
    container_name: master-api-gateway
    build:
      context: api-gateway/
      dockerfile: Dockerfile
    networks:
      - currency-network
    depends_on:
      - eureka-server
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
networks:
  currency-network:
